name: DeepSlateRP
version: '${version}'
main: ru.tnkv.dsrp.Main
api-version: 1.19
authors: [ tnkv, Zoga_com ]
website: "deepslate.ru"


commands:
   dice:
    usage: /dice
    permission: dsrp.use
    permission-message: "§cНет прав."
    description: "Бросить кости, через пробел можно указать максимальное возможное значение."
   try:
     usage: /try
     description: "Попытка сделать что-то, через пробел можно указать действие."
     permission: dsrp.use
     permission-message: "§cНет прав."
   me:
     usage: /me
     description: "Показать, что выполняешь какое-то действие."
     permission: dsrp.use
     permission-message: "§cНет прав."
   todo:
     usage: /todo
     description: "Выполнять действие во время выполнения другого."
     permission: dsrp.use
     permission-message: "§cНет прав."